[paths]
classic = ""
retail = ""
tbc = ""

[keybindings]
update_addon = "u"
update_all_addons = "U"
remove_addon = "r"
download_addon = "d"
install_addon = "i"
select_retail_version = "R"
select_classic_version = "C"
select_tbc_version = "T"
search_addon = "/"
next_tab = "l"
prev_tab = "h"
next_table_item = "j"
prev_table_item = "k"
quit = "q"
scroll_down_log = "J"
scroll_up_log = "K"

